name: Run Email Extraction Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Puedes cambiar la versión de Python según necesites

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener un requirements.txt con todas las dependencias

      # Install Ollama
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      # Pull the required models
      - name: Pull phi3.5 model
        run: ollama pull phi3.5

      - name: Pull llama3.2 model
        run: ollama pull llama3.2

      # Start Ollama serve
      - name: Start Ollama serve
        run: ollama serve &
        
      # Wait for Ollama to be ready
      - name: Wait for Ollama to be ready
        run: sleep 10  # Ajusta el tiempo si es necesario para que Ollama esté completamente listo
      
      # Run tests
      - name: Run tests
        run: pytest tests/test_email_extraction.py
